# Fabric Warehouse への接続設定
jaffle_shop:
  target: fabric-dev
  outputs:
    fabric-dev:
      type: fabric
      driver: "ODBC Driver 18 for SQL Server"
      server: "t5txzdn46dvuniywcpm5owcawm-bxibaf7eydnu5edyx5dy3yentq.datawarehouse.fabric.microsoft.com"
      port: 1433
      database: "jaffle_warehouse" # QUESTION:dbtは1つの会社で1つだが、databaseはどの単位が望ましい？
      schema: jaffle_training
      threads: 4
      authentication: ServicePrincipal
      tenant_id: "{{ env_var('AZURE_TENANT_ID') }}"
      client_id: "{{ env_var('AZURE_CLIENT_ID') }}"
      client_secret: "{{ env_var('AZURE_CLIENT_SECRET') }}"
