version: 2

sources:
  - name: crm_system
    description: "CRMシステム（営業システム）のデータソース"
    schema: crm_system
    tables:
      - name: sales_persons
        description: "営業担当者マスター"
        columns:
          - name: sales_person_id
            description: "営業担当者ID"
          - name: sales_person_name
            description: "営業担当者名"
          - name: phone_number
            description: "電話番号"
          - name: email
            description: "メールアドレス"
          - name: manager_id
            description: "上長ID"
      
      - name: channels
        description: "チャネルマスター"
        columns:
          - name: channel_id
            description: "チャネルID"
          - name: channel_name
            description: "チャネル名"
      
      - name: customers
        description: "顧客マスター（正規化：channel_idのみ）"
        columns:
          - name: customer_id
            description: "顧客ID"
          - name: customer_name
            description: "顧客名"
          - name: account_name
            description: "アカウント名"
          - name: phone_number
            description: "電話番号"
          - name: email
            description: "メールアドレス"
          - name: representative_name
            description: "代表者名"
          - name: channel_id
            description: "チャネルID（channelsテーブル参照）"
          - name: manager_name
            description: "上長名"
      
      - name: regions
        description: "地域マスター"
        columns:
          - name: region_id
            description: "地域ID"
          - name: region_name
            description: "地域名"
      
      - name: branches
        description: "支店マスター（正規化：region_idのみ）"
        columns:
          - name: branch_id
            description: "支店ID"
          - name: branch_name
            description: "支店名"
          - name: region_id
            description: "地域ID（regionsテーブル参照）"
      
      - name: stages
        description: "ステージマスター"
        columns:
          - name: stage_id
            description: "ステージID"
          - name: stage_name
            description: "ステージ名"
          - name: stage_order
            description: "ステージ順序"
      
      - name: opportunity_events
        description: "営業機会イベントテーブル（トランザクションデータ）"
        columns:
          - name: event_id
            description: "イベントID"
          - name: sales_person_id
            description: "営業担当者ID"
          - name: customer_id
            description: "顧客ID"
          - name: product_id
            description: "商品ID"
          - name: branch_id
            description: "支店ID"
          - name: event_timestamp
            description: "イベント発生日時"
          - name: stage_id
            description: "ステージID"
          - name: expected_amount
            description: "予想契約金額"
          - name: contract_amount
            description: "契約金額"

  - name: product_system
    description: "商品管理システムのデータソース"
    schema: source_products
    tables:
      - name: categories
        description: "カテゴリーマスター"
        columns:
          - name: category_id
            description: "カテゴリーID"
          - name: category_name
            description: "カテゴリ名"
      
      - name: services
        description: "サービスマスター"
        columns:
          - name: service_id
            description: "サービスID"
          - name: service_name
            description: "サービス名"
      
      - name: products
        description: "商品マスター（正規化：category_id, service_idのみ）"
        columns:
          - name: product_id
            description: "商品ID"
          - name: product_name
            description: "商品名"
          - name: category_id
            description: "カテゴリーID（categoriesテーブル参照）"
          - name: service_id
            description: "サービスID（servicesテーブル参照）"